### ISSUE TITLE
hero image not displayed properly between ipad to desktop

### ISSUE THREAD

**Issue by pHoeniX-svg** [pHoeniX-svg/url-shortener#18]
![Screenshot_1](https://user-images.githubusercontent.com/68931805/136636509-e5d8f794-4c62-4e09-b768-9da5e133d150.png)

**Comment by Melissacinta** [comment]
noted and fixed

![recording](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiZWViNTIyMGItY2Y0My00ZDcyLTlmNmUtNGNjMTgxOGRjOWUxIiwiZGVwbG95X2lkIjoiNjE2MWU0NmQxZWJlNzIwMDA4YjIyOTc5IiwiaWQiOiJlNmY3ZmU1MC0zNmI1LTQyNjUtYTZmYi05MGI2OTUwZWJkMTcifQ==)
